wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.13
    cli_version: 0.16.5
    framework: keras
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1718898323.0
    t:
      1:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      - 105
      2:
      - 2
      - 3
      - 5
      - 53
      - 55
      - 80
      - 105
      3:
      - 23
      4: 3.10.13
      5: 0.16.5
      8:
      - 1
      - 5
      13: linux-x86_64
